version: "3"
services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432

        environment:
            - POSTGRES_DB=testDB
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
            MYSQL_DATABASE: testDB
            MYSQL_USER: foo
            MYSQL_PASSWORD: bar
        ports:
            - 6033:3306
        volumes:
            - ./data/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
